### ISSUE TITLE
Support for LAN devices?

### ISSUE THREAD

**Issue by KennieNL** [kukulich/home-assistant-jablotron100#21]
Hi,

I don't know if it has been researched if it's easy to implement this for LAN support too?
I do not have my alarm system near my domotica server, so I can't connect to USB really.

It would be great if LAN (or via Jablotron Cloud) it would be possible to read the sensors.
Or are any serial to net supported?

**Comment by kukulich** [comment]
@KennieNL It may be possible to do it because:

- the mobile application can somehow manage the alarm
- F-Link/J-Link application can do it too

However we don’t know how both methods work. The USB solution is based on reverse engineering the communication. So someone has to reveal other type of communication first.

**Comment by kukulich** [comment]
The mobile application protocol is probably used in: https://github.com/F4stFr3ddy/homebridge-jablotron-alarm

**Comment by KennieNL** [comment]
@kukulich I've looked in the mobile application already, it isn't based anymore on that homebridge-jablotron API anymore, but a different one. That one is easy to reverse, but only is able to show the alarm status & arm/disarm the alarm... I would like the full benefits of F-Link/J-Link.

I'll see if I ever have the time to try and analyze the protocol
